/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-03-12 10:42:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import fr.simplon.models.Post;
import java.util.List;
import java.time.format.DateTimeFormatter;
import jakarta.servlet.http.HttpSession;

public final class feeds_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("fr.simplon.models.Post");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<Post> postList = (List<Post>) request.getAttribute("postList");
    String feedType = (String) request.getAttribute("feedType");
    if (feedType == null) feedType = "recommendations";
    DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd MMM yyyy · HH:mm");

    HttpSession currentSession = request.getSession(false);
    boolean isLogged = currentSession != null && currentSession.getAttribute("loggedUser") != null;
    String loggedUser = isLogged ? (String) currentSession.getAttribute("loggedUser") : null;
    String initAvatar = (loggedUser != null && !loggedUser.isEmpty())
        ? String.valueOf(loggedUser.charAt(0)).toUpperCase() : "?";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>Fil — Miniature</title>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=Inter:wght@300;400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("\r\n");
      out.write("    :root {\r\n");
      out.write("      --bg:        #f0ede8;\r\n");
      out.write("      --surface:   #faf9f7;\r\n");
      out.write("      --border:    #e0dbd2;\r\n");
      out.write("      --accent:    #1a1a1a;\r\n");
      out.write("      --accent2:   #3d3d3d;\r\n");
      out.write("      --pop:       #e85d3a;\r\n");
      out.write("      --pop-light: #fdf0ed;\r\n");
      out.write("      --text:      #1a1a1a;\r\n");
      out.write("      --muted:     #9a9590;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      background: var(--bg);\r\n");
      out.write("      color: var(--text);\r\n");
      out.write("      font-family: 'Inter', sans-serif;\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ── Header ── */\r\n");
      out.write("    header {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 0; left: 0; right: 0;\r\n");
      out.write("      z-index: 100;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      padding: 1.1rem 3rem;\r\n");
      out.write("      background: rgba(250,249,247,0.88);\r\n");
      out.write("      backdrop-filter: blur(14px);\r\n");
      out.write("      border-bottom: 1px solid var(--border);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-logo {\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: 1.4rem;\r\n");
      out.write("      font-weight: 800;\r\n");
      out.write("      letter-spacing: -0.02em;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: var(--accent);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-logo span { color: var(--pop); }\r\n");
      out.write("\r\n");
      out.write("    .nav-links {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 0.4rem;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a {\r\n");
      out.write("      font-size: 0.78rem;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      letter-spacing: 0.06em;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      padding: 0.45rem 0.9rem;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      transition: color 0.2s, background 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a:hover { color: var(--accent); background: var(--border); }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a.logout { color: var(--pop); }\r\n");
      out.write("    .nav-links a.logout:hover { background: var(--pop-light); }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a.btn-outline {\r\n");
      out.write("      border: 1.5px solid var(--border);\r\n");
      out.write("      color: var(--accent2);\r\n");
      out.write("    }\r\n");
      out.write("    .nav-links a.btn-outline:hover { border-color: var(--accent); background: var(--bg); }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a.btn-fill {\r\n");
      out.write("      background: var(--pop);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .nav-links a.btn-fill:hover { background: #d44f2e; }\r\n");
      out.write("\r\n");
      out.write("    /* ── Layout centré ── */\r\n");
      out.write("    .layout {\r\n");
      out.write("      max-width: 680px;\r\n");
      out.write("      margin: 0 auto;\r\n");
      out.write("      padding: 7rem 1.5rem 4rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ── Compose ── */\r\n");
      out.write("    .compose {\r\n");
      out.write("      background: var(--surface);\r\n");
      out.write("      border: 1px solid var(--border);\r\n");
      out.write("      border-radius: 16px;\r\n");
      out.write("      padding: 1.5rem;\r\n");
      out.write("      margin-bottom: 2rem;\r\n");
      out.write("      animation: fadeUp 0.5s ease both;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .compose-label {\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: 0.7rem;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      letter-spacing: 0.15em;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      color: var(--pop);\r\n");
      out.write("      margin-bottom: 0.75rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    textarea {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      background: var(--bg);\r\n");
      out.write("      border: 1.5px solid var(--border);\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      padding: 0.85rem 1rem;\r\n");
      out.write("      color: var(--text);\r\n");
      out.write("      font-family: 'Inter', sans-serif;\r\n");
      out.write("      font-size: 0.92rem;\r\n");
      out.write("      resize: vertical;\r\n");
      out.write("      min-height: 90px;\r\n");
      out.write("      outline: none;\r\n");
      out.write("      transition: border-color 0.2s, box-shadow 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    textarea::placeholder { color: var(--muted); }\r\n");
      out.write("    textarea:focus {\r\n");
      out.write("      border-color: var(--accent);\r\n");
      out.write("      box-shadow: 0 0 0 3px rgba(26,26,26,0.06);\r\n");
      out.write("      background: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .compose-footer {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: flex-end;\r\n");
      out.write("      margin-top: 0.75rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-primary {\r\n");
      out.write("      padding: 0.6rem 1.5rem;\r\n");
      out.write("      background: var(--pop);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: 0.8rem;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      letter-spacing: 0.06em;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: background 0.2s, transform 0.1s, box-shadow 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-primary:hover {\r\n");
      out.write("      background: #d44f2e;\r\n");
      out.write("      box-shadow: 0 4px 12px rgba(232,93,58,0.3);\r\n");
      out.write("    }\r\n");
      out.write("    .btn-primary:active { transform: scale(0.97); }\r\n");
      out.write("\r\n");
      out.write("    /* ── Tabs ── */\r\n");
      out.write("    .feed-tabs {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      margin-bottom: 1.5rem;\r\n");
      out.write("      border: 1px solid var(--border);\r\n");
      out.write("      border-radius: 12px;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      animation: fadeUp 0.5s ease 0.05s both;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feed-tabs a {\r\n");
      out.write("      flex: 1;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 0.75rem;\r\n");
      out.write("      font-size: 0.78rem;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      letter-spacing: 0.1em;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      background: var(--surface);\r\n");
      out.write("      transition: color 0.2s, background 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feed-tabs a:first-child { border-right: 1px solid var(--border); }\r\n");
      out.write("    .feed-tabs a:hover { color: var(--accent); background: var(--bg); }\r\n");
      out.write("    .feed-tabs a.active { color: var(--pop); background: var(--pop-light); font-weight: 700; }\r\n");
      out.write("\r\n");
      out.write("    /* ── Posts ── */\r\n");
      out.write("    .post-list {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      gap: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .post-card {\r\n");
      out.write("      background: var(--surface);\r\n");
      out.write("      border: 1px solid var(--border);\r\n");
      out.write("      border-radius: 16px;\r\n");
      out.write("      padding: 1.25rem 1.5rem;\r\n");
      out.write("      animation: fadeUp 0.5s ease both;\r\n");
      out.write("      transition: border-color 0.2s, box-shadow 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .post-card:hover {\r\n");
      out.write("      border-color: rgba(232,93,58,0.25);\r\n");
      out.write("      box-shadow: 0 2px 16px rgba(232,93,58,0.06);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .post-meta {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      margin-bottom: 0.75rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .post-owner {\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: 0.82rem;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      color: var(--pop);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .post-date {\r\n");
      out.write("      font-size: 0.72rem;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .post-content {\r\n");
      out.write("      font-size: 0.95rem;\r\n");
      out.write("      line-height: 1.7;\r\n");
      out.write("      color: var(--accent2);\r\n");
      out.write("      margin-bottom: 1rem;\r\n");
      out.write("      word-break: break-word;\r\n");
      out.write("      white-space: pre-wrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .post-actions {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 0.75rem;\r\n");
      out.write("      padding-top: 0.75rem;\r\n");
      out.write("      border-top: 1px solid var(--border);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-like {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 0.35rem;\r\n");
      out.write("      background: none;\r\n");
      out.write("      border: 1.5px solid var(--border);\r\n");
      out.write("      border-radius: 999px;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      font-family: 'Inter', sans-serif;\r\n");
      out.write("      font-size: 0.8rem;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      padding: 0.3rem 0.9rem;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: color 0.2s, border-color 0.2s, background 0.2s, transform 0.1s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-like:hover {\r\n");
      out.write("      color: var(--pop);\r\n");
      out.write("      border-color: var(--pop);\r\n");
      out.write("      background: var(--pop-light);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-like.liked {\r\n");
      out.write("      color: var(--pop);\r\n");
      out.write("      border-color: var(--pop);\r\n");
      out.write("      background: var(--pop-light);\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-like.liked:hover { transform: scale(1.04); }\r\n");
      out.write("\r\n");
      out.write("    .post-draft {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      font-size: 0.68rem;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      letter-spacing: 0.1em;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      border: 1px solid var(--border);\r\n");
      out.write("      border-radius: 999px;\r\n");
      out.write("      padding: 0.2rem 0.65rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ── Empty state ── */\r\n");
      out.write("    .empty {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 4rem 2rem;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      font-size: 0.9rem;\r\n");
      out.write("      line-height: 1.6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .empty-icon {\r\n");
      out.write("      font-size: 2.5rem;\r\n");
      out.write("      margin-bottom: 1rem;\r\n");
      out.write("      opacity: 0.3;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeUp {\r\n");
      out.write("      from { opacity: 0; transform: translateY(14px); }\r\n");
      out.write("      to   { opacity: 1; transform: translateY(0); }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 600px) {\r\n");
      out.write("      header { padding: 1rem 1.25rem; }\r\n");
      out.write("      .layout { padding: 6rem 1rem 3rem; }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <header>\r\n");
      out.write("    <a class=\"nav-logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/feeds\">Mini<span>ature</span></a>\r\n");
      out.write("    <nav class=\"nav-links\" aria-label=\"Navigation principale\">\r\n");
      out.write("      ");
 if (isLogged) { 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"logout\">Se déconnecter</a>\r\n");
      out.write("      ");
 } else { 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"btn-outline\">Se connecter</a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" class=\"btn-fill\">S'inscrire</a>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"layout\">\r\n");
      out.write("\r\n");
      out.write("    ");
 if (isLogged) { 
      out.write("\r\n");
      out.write("    <section class=\"compose\" aria-label=\"Nouveau post\">\r\n");
      out.write("      <p class=\"compose-label\">Nouveau post</p>\r\n");
      out.write("      <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/feeds\">\r\n");
      out.write("        <textarea name=\"newPost\" placeholder=\"Quoi de neuf ?\"></textarea>\r\n");
      out.write("        <div class=\"compose-footer\">\r\n");
      out.write("          <button type=\"submit\" class=\"btn-primary\">Publier →</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </section>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"feed-tabs\" role=\"tablist\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/feeds?type=recommendations\"\r\n");
      out.write("         class=\"");
      out.print( "recommendations".equals(feedType) ? "active" : "" );
      out.write("\"\r\n");
      out.write("         role=\"tab\">Recommandations</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/feeds?type=subscriptions\"\r\n");
      out.write("         class=\"");
      out.print( "subscriptions".equals(feedType) ? "active" : "" );
      out.write("\"\r\n");
      out.write("         role=\"tab\">Abonnements</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (postList == null || postList.isEmpty()) { 
      out.write("\r\n");
      out.write("      <div class=\"empty\">\r\n");
      out.write("        <div class=\"empty-icon\">✦</div>\r\n");
      out.write("        <p>Aucun post pour le moment.<br>Soyez le premier à publier !</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("      <div class=\"post-list\">\r\n");
      out.write("        ");
 for (Post post : postList) {
            boolean liked = post.isLiked();
            String likeClass = liked ? "btn-like liked" : "btn-like";
        
      out.write("\r\n");
      out.write("          <article class=\"post-card\">\r\n");
      out.write("            <div class=\"post-meta\">\r\n");
      out.write("              <span class=\"post-owner\">@ ");
      out.print( post.getOwnerUsername() );
      out.write("</span>\r\n");
      out.write("              <time class=\"post-date\" datetime=\"");
      out.print( post.getCreatedAt() );
      out.write("\">\r\n");
      out.write("                ");
      out.print( post.getCreatedAt().format(fmt) );
      out.write("\r\n");
      out.write("              </time>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"post-content\">");
      out.print( post.getContent() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"post-actions\">\r\n");
      out.write("              <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/feeds\">\r\n");
      out.write("                <input type=\"hidden\" name=\"buttonLike\" value=\"");
      out.print( post.getId() );
      out.write("\">\r\n");
      out.write("                <button type=\"submit\" class=\"");
      out.print( likeClass );
      out.write("\"\r\n");
      out.write("                        aria-label=\"");
      out.print( liked ? "Ne plus aimer" : "Aimer" );
      out.write("\">\r\n");
      out.write("                  ♥ ");
      out.print( liked ? "Aimé" : "J'aime" );
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("              </form>\r\n");
      out.write("              ");
 if (post.isDraft()) { 
      out.write("\r\n");
      out.write("                <span class=\"post-draft\">Brouillon</span>\r\n");
      out.write("              ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </article>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
