/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-03-16 09:38:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Date;
import jakarta.servlet.http.HttpSession;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String user = request.getParameter("user"); Date date = new Date(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>Accueil - Miniature</title>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=DM+Sans:wght@300;400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("\r\n");
      out.write("    :root {\r\n");
      out.write("      --bg:       #0d0d0f;\r\n");
      out.write("      --surface:  #16161a;\r\n");
      out.write("      --border:   #2a2a32;\r\n");
      out.write("      --accent:   #c8a96e;\r\n");
      out.write("      --accent2:  #e8c98e;\r\n");
      out.write("      --text:     #e8e6e0;\r\n");
      out.write("      --muted:    #6b6870;\r\n");
      out.write("      --danger:   #c0675a;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      background: var(--bg);\r\n");
      out.write("      color: var(--text);\r\n");
      out.write("      font-family: 'DM Sans', sans-serif;\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Grain overlay */\r\n");
      out.write("    body::before {\r\n");
      out.write("      content: '';\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      inset: 0;\r\n");
      out.write("      background-image: url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.04'/%3E%3C/svg%3E\");\r\n");
      out.write("      pointer-events: none;\r\n");
      out.write("      z-index: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Nav */\r\n");
      out.write("    nav {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 0; left: 0; right: 0;\r\n");
      out.write("      z-index: 100;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      padding: 1.25rem 3rem;\r\n");
      out.write("      border-bottom: 1px solid var(--border);\r\n");
      out.write("      background: rgba(13,13,15,0.85);\r\n");
      out.write("      backdrop-filter: blur(12px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-logo {\r\n");
      out.write("      font-family: 'Playfair Display', serif;\r\n");
      out.write("      font-size: 1.4rem;\r\n");
      out.write("      color: var(--accent);\r\n");
      out.write("      letter-spacing: 0.05em;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 0.5rem;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a {\r\n");
      out.write("      font-size: 0.8rem;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      letter-spacing: 0.08em;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      padding: 0.5rem 1rem;\r\n");
      out.write("      border-radius: 6px;\r\n");
      out.write("      transition: color 0.2s, background 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a:hover { color: var(--text); background: var(--border); }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a.logout {\r\n");
      out.write("      color: var(--danger);\r\n");
      out.write("      border: 1px solid transparent;\r\n");
      out.write("    }\r\n");
      out.write("    .nav-links a.logout:hover {\r\n");
      out.write("      background: rgba(192,103,90,0.1);\r\n");
      out.write("      border-color: var(--danger);\r\n");
      out.write("      color: var(--danger);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Hero */\r\n");
      out.write("    main {\r\n");
      out.write("      flex: 1;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      padding: 8rem 2rem 4rem;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      max-width: 640px;\r\n");
      out.write("      animation: fadeUp 0.8s ease both;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeUp {\r\n");
      out.write("      from { opacity: 0; transform: translateY(24px); }\r\n");
      out.write("      to   { opacity: 1; transform: translateY(0); }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero-eyebrow {\r\n");
      out.write("      font-size: 0.72rem;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      letter-spacing: 0.2em;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      color: var(--accent);\r\n");
      out.write("      margin-bottom: 1.5rem;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      gap: 0.75rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero-eyebrow::before,\r\n");
      out.write("    .hero-eyebrow::after {\r\n");
      out.write("      content: '';\r\n");
      out.write("      width: 32px;\r\n");
      out.write("      height: 1px;\r\n");
      out.write("      background: var(--accent);\r\n");
      out.write("      opacity: 0.5;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h1 {\r\n");
      out.write("      font-family: 'Playfair Display', serif;\r\n");
      out.write("      font-size: clamp(2.4rem, 6vw, 4rem);\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      line-height: 1.1;\r\n");
      out.write("      color: var(--text);\r\n");
      out.write("      margin-bottom: 1.25rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h1 span {\r\n");
      out.write("      color: var(--accent);\r\n");
      out.write("      font-style: italic;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero-sub {\r\n");
      out.write("      font-size: 0.95rem;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      line-height: 1.7;\r\n");
      out.write("      margin-bottom: 3rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Date badge */\r\n");
      out.write("    .date-badge {\r\n");
      out.write("      display: inline-flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 0.5rem;\r\n");
      out.write("      font-size: 0.75rem;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      border: 1px solid var(--border);\r\n");
      out.write("      border-radius: 999px;\r\n");
      out.write("      padding: 0.4rem 1rem;\r\n");
      out.write("      letter-spacing: 0.04em;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .date-badge::before {\r\n");
      out.write("      content: '';\r\n");
      out.write("      width: 6px; height: 6px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      background: var(--accent);\r\n");
      out.write("      opacity: 0.8;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Decorative background orb */\r\n");
      out.write("    .orb {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      width: 600px; height: 600px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      background: radial-gradient(circle, rgba(200,169,110,0.06) 0%, transparent 70%);\r\n");
      out.write("      top: 50%; left: 50%;\r\n");
      out.write("      transform: translate(-50%, -50%);\r\n");
      out.write("      pointer-events: none;\r\n");
      out.write("      z-index: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Footer */\r\n");
      out.write("    footer {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 1.5rem;\r\n");
      out.write("      font-size: 0.72rem;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      letter-spacing: 0.05em;\r\n");
      out.write("      border-top: 1px solid var(--border);\r\n");
      out.write("      position: relative;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"orb\"></div>\r\n");
      out.write("\r\n");
      out.write("  <nav>\r\n");
      out.write("    <a class=\"nav-logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/feeds\">Miniature</a>\r\n");
      out.write("    <div class=\"nav-links\">\r\n");
      out.write("      ");

          HttpSession currentSession = request.getSession(false);
          boolean isLogged = currentSession != null && currentSession.getAttribute("loggedUser") != null;
      
      out.write("\r\n");
      out.write("  \r\n");
      out.write("      ");
 if (!isLogged) { 
      out.write("\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Se connecter</a>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">S'inscrire</a>\r\n");
      out.write("      ");
 } else { 
      out.write("\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"logout\">Se déconnecter</a>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <main>\r\n");
      out.write("    <div class=\"hero\">\r\n");
      out.write("      <div class=\"hero-eyebrow\">Tableau de bord</div>\r\n");
      out.write("      <h1>Bienvenue, <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedUser}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>&nbsp;!</h1>\r\n");
      out.write("      <p class=\"hero-sub\">Vous êtes connecté à votre espace personnel.<br>Retrouvez ici toutes vos ressources.</p>\r\n");
      out.write("      <div class=\"date-badge\">");
      out.print(date);
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <footer>© 2025 Miniature — Tous droits réservés</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
