/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-03-12 10:54:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>Inscription - Miniature</title>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=Inter:wght@300;400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("\r\n");
      out.write("    :root {\r\n");
      out.write("      --bg:        #f0ede8;\r\n");
      out.write("      --surface:   #faf9f7;\r\n");
      out.write("      --border:    #e0dbd2;\r\n");
      out.write("      --accent:    #1a1a1a;\r\n");
      out.write("      --accent2:   #3d3d3d;\r\n");
      out.write("      --pop:       #e85d3a;\r\n");
      out.write("      --pop-light: #fdf0ed;\r\n");
      out.write("      --text:      #1a1a1a;\r\n");
      out.write("      --muted:     #9a9590;\r\n");
      out.write("      --danger:    #e85d3a;\r\n");
      out.write("      --danger-bg: #fdf0ed;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      background: var(--bg);\r\n");
      out.write("      color: var(--text);\r\n");
      out.write("      font-family: 'Inter', sans-serif;\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("      display: grid;\r\n");
      out.write("      grid-template-columns: 1fr 1fr;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ── Panneau gauche branding ── */\r\n");
      out.write("    .panel-brand {\r\n");
      out.write("      background: var(--accent);\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      padding: 3rem;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .panel-brand::before {\r\n");
      out.write("      content: '';\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      width: 500px; height: 500px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      border: 1px solid rgba(255,255,255,0.06);\r\n");
      out.write("      top: -100px; left: -100px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .panel-brand::after {\r\n");
      out.write("      content: '';\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      width: 300px; height: 300px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      border: 1px solid rgba(255,255,255,0.06);\r\n");
      out.write("      bottom: 80px; right: -80px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .brand-logo {\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: 1.6rem;\r\n");
      out.write("      font-weight: 800;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      letter-spacing: -0.02em;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .brand-logo span { color: var(--pop); }\r\n");
      out.write("\r\n");
      out.write("    .brand-tagline {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .brand-tagline h2 {\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: clamp(2rem, 3.5vw, 3rem);\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      line-height: 1.15;\r\n");
      out.write("      margin-bottom: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .brand-tagline p {\r\n");
      out.write("      font-size: 0.9rem;\r\n");
      out.write("      color: rgba(255,255,255,0.45);\r\n");
      out.write("      line-height: 1.6;\r\n");
      out.write("      max-width: 320px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Étapes d'inscription */\r\n");
      out.write("    .brand-steps {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      gap: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .step {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .step-number {\r\n");
      out.write("      width: 32px; height: 32px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      background: var(--pop);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: 0.85rem;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      flex-shrink: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .step-text {\r\n");
      out.write("      font-size: 0.85rem;\r\n");
      out.write("      color: rgba(255,255,255,0.6);\r\n");
      out.write("      line-height: 1.4;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .step-text strong {\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      display: block;\r\n");
      out.write("      font-size: 0.9rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ── Panneau droit formulaire ── */\r\n");
      out.write("    .panel-form {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      padding: 3rem 2rem;\r\n");
      out.write("      background: var(--surface);\r\n");
      out.write("      overflow-y: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-wrapper {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      max-width: 400px;\r\n");
      out.write("      animation: slideIn 0.5s ease both;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes slideIn {\r\n");
      out.write("      from { opacity: 0; transform: translateX(20px); }\r\n");
      out.write("      to   { opacity: 1; transform: translateX(0); }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-header {\r\n");
      out.write("      margin-bottom: 2rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-header h1 {\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: 1.9rem;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      letter-spacing: -0.02em;\r\n");
      out.write("      margin-bottom: 0.4rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-header p {\r\n");
      out.write("      font-size: 0.87rem;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Alert */\r\n");
      out.write("    .alert-error {\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      padding: 0.75rem 1rem;\r\n");
      out.write("      font-size: 0.82rem;\r\n");
      out.write("      margin-bottom: 1.5rem;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 0.6rem;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      background: var(--danger-bg);\r\n");
      out.write("      border: 1px solid rgba(232,93,58,0.2);\r\n");
      out.write("      color: var(--danger);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Fieldset / section */\r\n");
      out.write("    fieldset {\r\n");
      out.write("      border: none;\r\n");
      out.write("      margin-bottom: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    legend {\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: 0.72rem;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      letter-spacing: 0.12em;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      margin-bottom: 1rem;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 0.75rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    legend::after {\r\n");
      out.write("      content: '';\r\n");
      out.write("      flex: 1;\r\n");
      out.write("      height: 1px;\r\n");
      out.write("      background: var(--border);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-row {\r\n");
      out.write("      display: grid;\r\n");
      out.write("      grid-template-columns: 1fr 1fr;\r\n");
      out.write("      gap: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group { margin-bottom: 1rem; }\r\n");
      out.write("\r\n");
      out.write("    label {\r\n");
      out.write("      display: block;\r\n");
      out.write("      font-size: 0.78rem;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      color: var(--accent2);\r\n");
      out.write("      margin-bottom: 0.45rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      background: var(--bg);\r\n");
      out.write("      border: 1.5px solid var(--border);\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      padding: 0.8rem 1rem;\r\n");
      out.write("      color: var(--text);\r\n");
      out.write("      font-family: 'Inter', sans-serif;\r\n");
      out.write("      font-size: 0.9rem;\r\n");
      out.write("      transition: border-color 0.2s, box-shadow 0.2s, background 0.2s;\r\n");
      out.write("      outline: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input::placeholder { color: var(--muted); }\r\n");
      out.write("\r\n");
      out.write("    input:focus {\r\n");
      out.write("      border-color: var(--accent);\r\n");
      out.write("      background: #fff;\r\n");
      out.write("      box-shadow: 0 0 0 3px rgba(26,26,26,0.06);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-submit {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      margin-top: 1rem;\r\n");
      out.write("      padding: 0.9rem;\r\n");
      out.write("      background: var(--pop);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      font-family: 'Syne', sans-serif;\r\n");
      out.write("      font-size: 0.9rem;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      letter-spacing: 0.02em;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: background 0.2s, transform 0.1s, box-shadow 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-submit:hover {\r\n");
      out.write("      background: #d44f2e;\r\n");
      out.write("      box-shadow: 0 4px 16px rgba(232,93,58,0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-submit:active { transform: scale(0.98); }\r\n");
      out.write("\r\n");
      out.write("    .form-footer {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-top: 1.5rem;\r\n");
      out.write("      font-size: 0.82rem;\r\n");
      out.write("      color: var(--muted);\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      gap: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-footer a {\r\n");
      out.write("      color: var(--accent);\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      border-bottom: 1px solid transparent;\r\n");
      out.write("      transition: border-color 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-footer a:hover { border-color: var(--accent); }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("      body { grid-template-columns: 1fr; }\r\n");
      out.write("      .panel-brand { display: none; }\r\n");
      out.write("      .panel-form { padding: 2rem 1.5rem; }\r\n");
      out.write("      .form-row { grid-template-columns: 1fr; }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- Panneau gauche : branding -->\r\n");
      out.write("  <aside class=\"panel-brand\" aria-hidden=\"true\">\r\n");
      out.write("    <a class=\"brand-logo\" href=\"#\">Mini<span>ature</span></a>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"brand-tagline\">\r\n");
      out.write("      <h2>Rejoignez la communauté.</h2>\r\n");
      out.write("      <p>Créez votre profil en quelques secondes et commencez à partager avec le monde.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"brand-steps\" aria-label=\"Étapes d'inscription\">\r\n");
      out.write("      <div class=\"step\">\r\n");
      out.write("        <span class=\"step-number\">1</span>\r\n");
      out.write("        <div class=\"step-text\">\r\n");
      out.write("          <strong>Créez votre profil</strong>\r\n");
      out.write("          Choisissez un pseudo unique\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"step\">\r\n");
      out.write("        <span class=\"step-number\">2</span>\r\n");
      out.write("        <div class=\"step-text\">\r\n");
      out.write("          <strong>Suivez des membres</strong>\r\n");
      out.write("          Abonnez-vous aux profils qui vous inspirent\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"step\">\r\n");
      out.write("        <span class=\"step-number\">3</span>\r\n");
      out.write("        <div class=\"step-text\">\r\n");
      out.write("          <strong>Publiez et likez</strong>\r\n");
      out.write("          Partagez vos idées et réagissez aux posts\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("\r\n");
      out.write("  <!-- Formulaire principal -->\r\n");
      out.write("  <main class=\"panel-form\">\r\n");
      out.write("    <div class=\"form-wrapper\">\r\n");
      out.write("\r\n");
      out.write("      <header class=\"form-header\">\r\n");
      out.write("        <h1>Créer un compte</h1>\r\n");
      out.write("        <p>Gratuit et sans engagement.</p>\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("      ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("        <div class=\"alert-error\" role=\"alert\">✕ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" novalidate>\r\n");
      out.write("\r\n");
      out.write("        <fieldset>\r\n");
      out.write("          <legend>Identité</legend>\r\n");
      out.write("          <div class=\"form-row\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"username\">Nom d'utilisateur</label>\r\n");
      out.write("              <input type=\"text\" id=\"username\" name=\"username\"\r\n");
      out.write("                     placeholder=\"username\" autocomplete=\"username\" required />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"email\">Email</label>\r\n");
      out.write("              <input type=\"email\" id=\"email\" name=\"email\"\r\n");
      out.write("                     placeholder=\"you@mail.com\" autocomplete=\"email\" required />\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <fieldset>\r\n");
      out.write("          <legend>Sécurité</legend>\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label for=\"password\">Mot de passe</label>\r\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\"\r\n");
      out.write("                   placeholder=\"••••••••\" autocomplete=\"new-password\" required />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label for=\"confirmPassword\">Confirmation</label>\r\n");
      out.write("            <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\"\r\n");
      out.write("                   placeholder=\"••••••••\" autocomplete=\"new-password\" required />\r\n");
      out.write("          </div>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"btn-submit\">Créer mon compte →</button>\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("      <footer class=\"form-footer\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Déjà un compte ?</a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\">Retour à l'accueil</a>\r\n");
      out.write("      </footer>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
